# @package _group_
name: "vihe"
variant: "base"
resume: ""
add_depth: true
add_proprio: true
add_lang: true
add_corr: true
add_pixel_loc: true
pe_fix: true
weight_tie_layers: false

im_channels: 64
lang_dim: 512
lang_len: 77
img_size: 110
img_patch_size: 11
attn_dim: 480
attn_heads: 8
attn_dropout: 0.1
final_dim: 64
self_cross_ver: 1
feat_dim: 220
proprio_dim: 4
img_feat_dim: 3
depth: 8
attn_dim_head: 64
img_aug: 0.1
gt_hm_sigma: 1.5
add_rgc_loss: true
lr: 0.0001
lambda_weight_l2: 1.0e-06
lr_cos_dec: true
num_rotation_classes: 72
optimizer_type: lamb
transform_augmentation: true
transform_augmentation_rpy:
- 0.0
- 0.0
- 45.0
transform_augmentation_xyz:
- 0.125
- 0.125
- 0.125
warmup_steps: 2000
move_pc_in_bound: true
place_with_mean: false

activation: "lrelu"

zoom_in: true
rotary_enc: true
rot_offset: true
merge: false
perturb_eye: true
pred_goal: false
act_cot: false
cross_action: false
cross_stage: true
dyn_dist: 0.001
high_res: false
img_init: false
mae: false
mae_beta: 1.0
mae_detach: false
mask_ratio: 0.0